#domain: tracylmt.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#url: https://tracylmt.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /output_local      # place folder name if the site is served in a subfolder
source: ./output_local        # deploy files in output_local only
destination: ./docs           # config requirement by github pages
regenerate: true
github: [metadata]